# Generated by Django 3.0.3 on 2020-05-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='API/static')),
            ],
            options={
                'ordering': ('image',),
            },
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('dateofBirth', models.DateField(null=True)),
                ('mallName', models.CharField(blank=True, max_length=200, null=True)),
                ('mallId', models.CharField(blank=True, max_length=200, null=True)),
                ('imageType', models.CharField(blank=True, max_length=200, null=True)),
                ('userId', models.CharField(blank=True, max_length=200, null=True)),
                ('mallGroupId', models.CharField(blank=True, max_length=200, null=True)),
                ('attachedImages', models.ManyToManyField(blank=True, related_name='Images', to='API.Image')),
            ],
            options={
                'ordering': ('mallName',),
            },
        ),
    ]
